size = 12
line_gap = 1
space_w = 7

[[glyphs]]
chr = "\u0000"
x = 7
y = 77
w = 6
h = 9
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = '!'
x = 61
y = 39
w = 2
h = 7
off_x = 2
off_y = -7
adv = 7

[[glyphs]]
chr = '"'
x = 49
y = 85
w = 5
h = 3
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '#'
x = 55
y = 24
w = 5
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = '$'
x = 28
y = 36
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '%'
x = 28
y = 44
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '&'
x = 0
y = 121
w = 6
h = 6
off_x = 0
off_y = -6
adv = 7

[[glyphs]]
chr = "'"
x = 55
y = 89
w = 2
h = 3
off_x = 2
off_y = -7
adv = 7

[[glyphs]]
chr = '('
x = 42
y = 42
w = 4
h = 9
off_x = 1
off_y = -8
adv = 7

[[glyphs]]
chr = ')'
x = 42
y = 52
w = 4
h = 9
off_x = 1
off_y = -8
adv = 7

[[glyphs]]
chr = '*'
x = 48
y = 24
w = 6
h = 5
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '+'
x = 55
y = 30
w = 5
h = 5
off_x = 0
off_y = -6
adv = 7

[[glyphs]]
chr = ','
x = 54
y = 93
w = 3
h = 3
off_x = 1
off_y = -2
adv = 7

[[glyphs]]
chr = '-'
x = 14
y = 125
w = 5
h = 1
off_x = 0
off_y = -4
adv = 7

[[glyphs]]
chr = '.'
x = 56
y = 101
w = 2
h = 2
off_x = 2
off_y = -2
adv = 7

[[glyphs]]
chr = '/'
x = 42
y = 24
w = 5
h = 8
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '0'
x = 28
y = 52
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '1'
x = 28
y = 60
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '2'
x = 28
y = 68
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '3'
x = 28
y = 76
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '4'
x = 28
y = 84
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '5'
x = 28
y = 92
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '6'
x = 28
y = 100
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '7'
x = 28
y = 108
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '8'
x = 28
y = 116
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '9'
x = 35
y = 0
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = ':'
x = 53
y = 98
w = 2
h = 5
off_x = 2
off_y = -5
adv = 7

[[glyphs]]
chr = ';'
x = 61
y = 24
w = 3
h = 6
off_x = 1
off_y = -5
adv = 7

[[glyphs]]
chr = '<'
x = 54
y = 64
w = 4
h = 5
off_x = 1
off_y = -6
adv = 7

[[glyphs]]
chr = '='
x = 49
y = 89
w = 5
h = 3
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = '>'
x = 54
y = 70
w = 4
h = 5
off_x = 1
off_y = -6
adv = 7

[[glyphs]]
chr = '?'
x = 42
y = 0
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '@'
x = 49
y = 0
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'A'
x = 56
y = 0
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'B'
x = 63
y = 0
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'C'
x = 70
y = 0
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'D'
x = 77
y = 0
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'E'
x = 84
y = 0
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'F'
x = 91
y = 0
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'G'
x = 98
y = 0
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'H'
x = 105
y = 0
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'I'
x = 112
y = 0
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'J'
x = 119
y = 0
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'K'
x = 35
y = 8
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'L'
x = 42
y = 8
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'M'
x = 49
y = 8
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'N'
x = 56
y = 8
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'O'
x = 63
y = 8
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'P'
x = 70
y = 8
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'Q'
x = 14
y = 80
w = 6
h = 8
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'R'
x = 77
y = 8
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'S'
x = 84
y = 8
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'T'
x = 91
y = 8
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'U'
x = 98
y = 8
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'V'
x = 105
y = 8
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'W'
x = 112
y = 8
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'X'
x = 119
y = 8
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'Y'
x = 35
y = 16
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'Z'
x = 42
y = 16
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '['
x = 42
y = 62
w = 4
h = 9
off_x = 1
off_y = -8
adv = 7

[[glyphs]]
chr = '\'
x = 42
y = 33
w = 5
h = 8
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = ']'
x = 42
y = 72
w = 4
h = 9
off_x = 1
off_y = -8
adv = 7

[[glyphs]]
chr = '^'
x = 57
y = 54
w = 5
h = 4
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '_'
x = 20
y = 126
w = 5
h = 1
off_x = 0
off_y = -1
adv = 7

[[glyphs]]
chr = '`'
x = 49
y = 110
w = 4
h = 3
off_x = 1
off_y = -7
adv = 7

[[glyphs]]
chr = 'a'
x = 48
y = 30
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'b'
x = 49
y = 16
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'c'
x = 48
y = 36
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'd'
x = 56
y = 16
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'e'
x = 47
y = 49
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'f'
x = 63
y = 16
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'g'
x = 14
y = 89
w = 6
h = 8
off_x = 0
off_y = -6
adv = 7

[[glyphs]]
chr = 'h'
x = 70
y = 16
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'i'
x = 77
y = 16
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'j'
x = 7
y = 87
w = 6
h = 9
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'k'
x = 84
y = 16
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'l'
x = 91
y = 16
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'm'
x = 47
y = 55
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'n'
x = 47
y = 61
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'o'
x = 47
y = 67
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'p'
x = 98
y = 16
w = 6
h = 7
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'q'
x = 105
y = 16
w = 6
h = 7
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'r'
x = 47
y = 73
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 's'
x = 42
y = 89
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 't'
x = 112
y = 16
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'u'
x = 42
y = 95
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'v'
x = 42
y = 101
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'w'
x = 42
y = 107
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'x'
x = 42
y = 113
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'y'
x = 119
y = 16
w = 6
h = 7
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'z'
x = 42
y = 119
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = '{'
x = 7
y = 97
w = 6
h = 9
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = '|'
x = 54
y = 54
w = 2
h = 9
off_x = 2
off_y = -8
adv = 7

[[glyphs]]
chr = '}'
x = 7
y = 107
w = 6
h = 9
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = '~'
x = 28
y = 124
w = 6
h = 3
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = '¡'
x = 64
y = 39
w = 2
h = 7
off_x = 2
off_y = -5
adv = 7

[[glyphs]]
chr = '¢'
x = 42
y = 82
w = 6
h = 6
off_x = 0
off_y = -6
adv = 7

[[glyphs]]
chr = '£'
x = 35
y = 24
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '¥'
x = 35
y = 32
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '©'
x = 14
y = 98
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = '«'
x = 55
y = 36
w = 5
h = 5
off_x = 0
off_y = -6
adv = 7

[[glyphs]]
chr = '®'
x = 14
y = 107
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = '°'
x = 57
y = 59
w = 5
h = 4
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '»'
x = 54
y = 48
w = 5
h = 5
off_x = 0
off_y = -6
adv = 7

[[glyphs]]
chr = '¿'
x = 35
y = 40
w = 6
h = 7
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'À'
x = 0
y = 0
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Á'
x = 0
y = 11
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Â'
x = 0
y = 22
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Ã'
x = 0
y = 33
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Ä'
x = 7
y = 117
w = 6
h = 9
off_x = 0
off_y = -9
adv = 7

[[glyphs]]
chr = 'Å'
x = 14
y = 0
w = 6
h = 9
off_x = 0
off_y = -9
adv = 7

[[glyphs]]
chr = 'Æ'
x = 35
y = 48
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'Ç'
x = 14
y = 10
w = 6
h = 9
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'È'
x = 0
y = 44
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'É'
x = 0
y = 55
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Ê'
x = 0
y = 66
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Ë'
x = 14
y = 20
w = 6
h = 9
off_x = 0
off_y = -9
adv = 7

[[glyphs]]
chr = 'Ì'
x = 0
y = 77
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Í'
x = 0
y = 88
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Î'
x = 0
y = 99
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Ï'
x = 14
y = 30
w = 6
h = 9
off_x = 0
off_y = -9
adv = 7

[[glyphs]]
chr = 'Ñ'
x = 0
y = 110
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Ò'
x = 7
y = 0
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Ó'
x = 7
y = 11
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Ô'
x = 7
y = 22
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Õ'
x = 7
y = 33
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Ö'
x = 14
y = 40
w = 6
h = 9
off_x = 0
off_y = -9
adv = 7

[[glyphs]]
chr = 'Ù'
x = 7
y = 44
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Ú'
x = 7
y = 55
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Û'
x = 7
y = 66
w = 6
h = 10
off_x = 0
off_y = -10
adv = 7

[[glyphs]]
chr = 'Ü'
x = 14
y = 50
w = 6
h = 9
off_x = 0
off_y = -9
adv = 7

[[glyphs]]
chr = 'ß'
x = 35
y = 56
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'à'
x = 14
y = 116
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'á'
x = 21
y = 0
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'â'
x = 21
y = 9
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'ã'
x = 21
y = 18
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'ä'
x = 35
y = 64
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'å'
x = 21
y = 27
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'æ'
x = 49
y = 79
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'ç'
x = 35
y = 72
w = 6
h = 7
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'è'
x = 21
y = 36
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'é'
x = 21
y = 45
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'ê'
x = 21
y = 54
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'ë'
x = 35
y = 80
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'ì'
x = 21
y = 63
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'í'
x = 21
y = 72
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'î'
x = 21
y = 81
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'ï'
x = 35
y = 88
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'ñ'
x = 21
y = 90
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'ò'
x = 21
y = 99
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'ó'
x = 21
y = 108
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'ô'
x = 21
y = 117
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'õ'
x = 28
y = 0
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'ö'
x = 35
y = 96
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'ù'
x = 28
y = 9
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'ú'
x = 28
y = 18
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'û'
x = 28
y = 27
w = 6
h = 8
off_x = 0
off_y = -8
adv = 7

[[glyphs]]
chr = 'ü'
x = 35
y = 104
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'ÿ'
x = 14
y = 60
w = 6
h = 9
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'Œ'
x = 35
y = 112
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = 'œ'
x = 54
y = 42
w = 6
h = 5
off_x = 0
off_y = -5
adv = 7

[[glyphs]]
chr = 'Ÿ'
x = 14
y = 70
w = 6
h = 9
off_x = 0
off_y = -9
adv = 7

[[glyphs]]
chr = 'ẞ'
x = 47
y = 42
w = 6
h = 6
off_x = 0
off_y = -6
adv = 7

[[glyphs]]
chr = '–'
x = 60
y = 52
w = 5
h = 1
off_x = 0
off_y = -4
adv = 7

[[glyphs]]
chr = '—'
x = 53
y = 108
w = 5
h = 1
off_x = 0
off_y = -4
adv = 7

[[glyphs]]
chr = '‘'
x = 53
y = 104
w = 3
h = 3
off_x = 1
off_y = -7
adv = 7

[[glyphs]]
chr = '’'
x = 56
y = 97
w = 3
h = 3
off_x = 1
off_y = -7
adv = 7

[[glyphs]]
chr = '‚'
x = 55
y = 85
w = 3
h = 3
off_x = 1
off_y = -1
adv = 7

[[glyphs]]
chr = '“'
x = 60
y = 48
w = 6
h = 3
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '”'
x = 61
y = 31
w = 6
h = 3
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '„'
x = 65
y = 24
w = 6
h = 3
off_x = 0
off_y = -1
adv = 7

[[glyphs]]
chr = '•'
x = 49
y = 93
w = 4
h = 4
off_x = 1
off_y = -5
adv = 7

[[glyphs]]
chr = '…'
x = 65
y = 28
w = 5
h = 1
off_x = 0
off_y = -1
adv = 7

[[glyphs]]
chr = '‹'
x = 49
y = 98
w = 3
h = 5
off_x = 1
off_y = -6
adv = 7

[[glyphs]]
chr = '›'
x = 49
y = 104
w = 3
h = 5
off_x = 1
off_y = -6
adv = 7

[[glyphs]]
chr = '€'
x = 35
y = 120
w = 6
h = 7
off_x = 0
off_y = -7
adv = 7

[[glyphs]]
chr = '™'
x = 61
y = 35
w = 6
h = 3
off_x = 0
off_y = -8
adv = 7
